language: python
python:
- '3.7'
- '3.8'
- 3.8-dev
- nightly
install:
- pip install Sphinx
script:
- cd docs
- make clean
- make html
- touch build/html/.nojekyll
deploy:
  - provider: pages:git
    verbose: true
    token: $GITHUB_TOKEN
    edge: true
    local_dir: ./docs/build/html/
